import React, { useState, useEffect } from 'react';
import { Item, Person, Expense } from './types';
import PackingTab from './components/PackingTab';
import ExpenseTab from './components/ExpenseTab';
import { ClipboardList, DollarSign, Tent } from 'lucide-react';
import * as itemService from './services/itemsService';
import * as expenseService from './services/expensesService';
import { initializeItems, subscribeToItems, seedItems } from './services/itemsService';
import { subscribeToExpenses } from './services/expensesService';
import { initializePeople, seedPeople, subscribeToPeople } from './services/peopleService';
import { migrateFromLocalStorage } from './utils/migration';
import { Database, AlertCircle, PartyPopper, Timer, Trophy } from 'lucide-react';
import FunTab from './components/FunTab';

// Helper to extract number from string like "x2"
const extractQuantity = (str?: string): number => {
  if (!str) return 1;
  const match = str.match(/\d+/);
  return match ? parseInt(match[0], 10) : 1;
};

// Main App Component
const App: React.FC = () => {
  // State
  // State
  const [activeTab, setActiveTab] = useState<'packing' | 'expenses' | 'fun'>('packing');

  // Countdown Logic
  const [timeLeft, setTimeLeft] = useState({ days: 0, hours: 0, minutes: 0 });

  useEffect(() => {
    const targetDate = new Date('2026-02-14T00:00:00');

    const updateTimer = () => {
      const now = new Date();
      const difference = targetDate.getTime() - now.getTime();

      if (difference > 0) {
        const days = Math.floor(difference / (1000 * 60 * 60 * 24));
        const hours = Math.floor((difference / (1000 * 60 * 60)) % 24);
        const minutes = Math.floor((difference / 1000 / 60) % 60);
        setTimeLeft({ days, hours, minutes });
      } else {
        setTimeLeft({ days: 0, hours: 0, minutes: 0 });
      }
    };

    updateTimer();
    const timer = setInterval(updateTimer, 60000); // Update every minute is enough
    return () => clearInterval(timer);
  }, []);

  // Data State
  const [people, setPeople] = useState<Person[]>([]);
  const [items, setItems] = useState<Item[]>([]);
  const [expenses, setExpenses] = useState<Expense[]>([]);
  const [connectionError, setConnectionError] = useState<string | null>(null);

  // Initialization & Subscriptions
  useEffect(() => {
    // Initialize default data if collections are empty
    const initData = async () => {
      await initializePeople();
      await initializeItems();
    };
    initData();

    // Subscribe to real-time updates
    const unsubscribePeople = subscribeToPeople(setPeople, (err) => setConnectionError("Error cargando gente: " + err.message));
    const unsubscribeItems = subscribeToItems(setItems, (err) => setConnectionError("Error cargando ítems: " + err.message));
    const unsubscribeExpenses = subscribeToExpenses(setExpenses, (err) => setConnectionError("Error cargando gastos: " + err.message));

    return () => {
      unsubscribePeople();
      unsubscribeItems();
      unsubscribeExpenses();
    };
  }, []);

  // Handlers
  const handleAddItem = (item: Item) => {
    // We ignore the ID generated by the UI and let Firestore generate one
    // eslint-disable-next-line @typescript-eslint/no-unused-vars
    const { id, ...rest } = item;
    itemService.addItem(rest);
  };

  const handleDeleteItem = (id: string) => itemService.deleteItem(id);

  const handleUpdateItem = (updatedItem: Item) => {
    // eslint-disable-next-line @typescript-eslint/no-unused-vars
    const { id, ...updates } = updatedItem;
    itemService.updateItem(id, updates);
  };

  const handleAddExpense = (expense: Expense) => {
    // eslint-disable-next-line @typescript-eslint/no-unused-vars
    const { id, ...rest } = expense;
    expenseService.addExpense(rest);
  };

  const handleDeleteExpense = (id: string) => expenseService.deleteExpense(id);

  const handleUpdateExpense = (id: string, updates: Partial<Expense>) => {
    expenseService.updateExpense(id, updates);
  };

  return (
    <div className="min-h-screen bg-[#FFF8F0] text-slate-900 font-sans selection:bg-orange-200">
      {/* Header with Illustration Vibes */}
      <header className="bg-gradient-to-b from-[#FF9F68] to-[#FFCBA4] pt-12 pb-24 px-6 border-b-4 border-black relative overflow-hidden">
        {/* Decorative Mountain Shapes */}
        <div className="absolute bottom-0 left-0 w-full h-16 pointer-events-none">
          <svg viewBox="0 0 1440 320" className="w-full h-full preserve-aspect-ratio-none">
            <path fill="#FFF8F0" fillOpacity="1" d="M0,224L48,213.3C96,203,192,181,288,181.3C384,181,480,203,576,224C672,245,768,267,864,250.7C960,235,1056,181,1152,165.3C1248,149,1344,171,1392,181.3L1440,192L1440,320L1392,320C1344,320,1248,320,1152,320C1056,320,960,320,864,320C768,320,672,320,576,320C480,320,384,320,288,320C192,320,96,320,48,320L0,320Z"></path>
          </svg>
        </div>

        <div className="max-w-2xl mx-auto relative z-10 text-center">
          <div className="inline-block bg-white border-2 border-black rounded-full p-3 mb-4 shadow-[4px_4px_0px_0px_rgba(0,0,0,1)] animate-bounce-slow">
            <Tent className="w-8 h-8 text-orange-500" strokeWidth={2.5} />
          </div>
          <h1 className="text-5xl font-black tracking-tight text-slate-900 uppercase leading-none mb-2 drop-shadow-sm">
            Valle Hermoso<br /><span className="text-white text-stroke-black">2026</span>
          </h1>

          {/* Countdown Manija */}
          <div className="flex justify-center gap-4 my-6">
            <div className="bg-black text-white p-2 rounded-lg border-2 border-white shadow-lg text-center min-w-[60px]">
              <span className="block text-2xl font-black">{timeLeft.days}</span>
              <span className="text-[10px] uppercase font-bold text-slate-400">Días</span>
            </div>
            <div className="bg-black text-white p-2 rounded-lg border-2 border-white shadow-lg text-center min-w-[60px]">
              <span className="block text-2xl font-black">{timeLeft.hours}</span>
              <span className="text-[10px] uppercase font-bold text-slate-400">Hs</span>
            </div>
            <div className="bg-black text-white p-2 rounded-lg border-2 border-white shadow-lg text-center min-w-[60px]">
              <span className="block text-2xl font-black">{timeLeft.minutes}</span>
              <span className="text-[10px] uppercase font-bold text-slate-400">Min</span>
            </div>
          </div>

          <p className="text-slate-800 font-bold mt-2 text-lg">
            ¡Falta poco para darnosla en la pera! 🍐
          </p>
        </div>
      </header>

      {/* Main Content Area - overlaps header */}
      <main className="max-w-2xl mx-auto px-4 -mt-12 relative z-20">

        {connectionError && (
          <div className="bg-red-100 border-2 border-red-500 rounded-xl p-4 mb-6 shadow-[4px_4px_0px_0px_rgba(239,68,68,1)] flex gap-3 items-start animate-pulse">
            <AlertCircle className="w-6 h-6 text-red-600 flex-shrink-0" />
            <div>
              <h3 className="font-black text-red-700 uppercase tracking-wide text-sm">Error de Conexión</h3>
              <p className="text-red-800 text-sm font-medium">{connectionError}</p>
            </div>
          </div>
        )}

        {/* Navigation Tabs */}
        <div className="bg-white rounded-xl border-2 border-black p-2 flex gap-2 mb-8 shadow-[6px_6px_0px_0px_rgba(0,0,0,1)]">
          <button
            onClick={() => setActiveTab('packing')}
            className={`flex-1 py-3 rounded-lg flex items-center justify-center gap-2 text-base font-bold transition-all border-2 ${activeTab === 'packing'
              ? 'bg-[#95D1CC] text-slate-900 border-black shadow-[2px_2px_0px_0px_rgba(0,0,0,1)] translate-y-[-2px]'
              : 'bg-transparent text-slate-500 border-transparent hover:bg-slate-50'
              }`}
          >
            <ClipboardList className="w-5 h-5" strokeWidth={2.5} />
            Mochila
          </button>
          <button
            onClick={() => setActiveTab('expenses')}
            className={`flex-1 py-3 rounded-lg flex items-center justify-center gap-2 text-base font-bold transition-all border-2 ${activeTab === 'expenses'
              ? 'bg-[#95D1CC] text-slate-900 border-black shadow-[2px_2px_0px_0px_rgba(0,0,0,1)] translate-y-[-2px]'
              : 'bg-transparent text-slate-500 border-transparent hover:bg-slate-50'
              }`}
          >
            <DollarSign className="w-5 h-5" strokeWidth={2.5} />
            Gastos
          </button>
          <button
            onClick={() => setActiveTab('fun')}
            className={`flex-1 py-3 rounded-lg flex items-center justify-center gap-2 text-base font-bold transition-all border-2 ${activeTab === 'fun'
              ? 'bg-[#FF9F68] text-slate-900 border-black shadow-[2px_2px_0px_0px_rgba(0,0,0,1)] translate-y-[-2px]'
              : 'bg-transparent text-slate-500 border-transparent hover:bg-slate-50'
              }`}
          >
            <Trophy className="w-5 h-5" strokeWidth={2.5} />
            Posiciones
          </button>
        </div>

        {/* Tab Content */}
        <div className="animate-in fade-in zoom-in-95 duration-300">
          {activeTab === 'packing' ? (
            <PackingTab
              items={items}
              people={people}
              addItem={handleAddItem}
              deleteItem={handleDeleteItem}
              updateItem={handleUpdateItem}
            />
          ) : activeTab === 'expenses' ? (
            <ExpenseTab
              expenses={expenses}
              people={people}
              addExpense={handleAddExpense}
              deleteExpense={handleDeleteExpense}
              updateExpense={handleUpdateExpense}
            />
          ) : (
            <FunTab
              items={items}
              people={people}
              expenses={expenses}
            />
          )}
        </div>
      </main>

      {/* Footer */}
      <footer className="py-12 text-center space-y-4">
        <p className="text-slate-400 text-sm font-bold tracking-widest uppercase">
          Hecho con ❤️ para la banda
        </p>
      </footer>
    </div>
  );
};

export default App;